### PR TITLE
Fix undefined index in api_auth.php

### LINKED ISSUE #362: Undefined index: PHP_AUTH_DIGEST
**Describe the bug**
getting blank screen when access

**To Reproduce**
1. its working when fresh install
2. but not working after clearing the cookie

**Screenshots**
blank screem

**Desktop (please complete the following information):**
 - OS: Centos 6 
 - Browser Firefox 86.0b7 (64-bit)

**Additional context**
this is error
```
Array
(
    [type] => 8
    [message] => Undefined index: PHP_AUTH_DIGEST
    [file] => /home/script/public_html/open356/plugins/api_auth.php
    [line] => 25
)
```

### PR DESCRIPTION
**Pull request by xZToxicZx**
Fix for #362

### CODE REVIEW

**Comment by mikespears** [comment]
Looks good. Approved.

**Comment by devotedsouls** [comment]
Approved by PM Shea

**Review by mikespears — APPROVED** [review]

**Review by ItsAGeekThing — CHANGES_REQUESTED** [review]
@xZToxicZx discovered that another bug may have been introduced from this pull request (via Discord).

PR363

**Review by mikespears — APPROVED** [review]

**Review by ItsAGeekThing — APPROVED** [review]
Looks good in my test environment. 👍

**Pull request merged**
