### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cambridgeport90**
I fixed a typo or two. Support isn't spelled with three P's, last I checked...

### CODE REVIEW

**Review by devotedsouls — CHANGES_REQUESTED** [review]
Fix the alignment for center to not show in public; its currently showing...

Clear spacing in you (line 36)

**Comment by Cambridgeport90** [comment]
Thanks for fixing that. I didn't even notice. My bad.

**Review by Cambridgeport90 — COMMENTED** [review]
I think this is all set?

**Review by devotedsouls — APPROVED** [review]
Approval sent. Signed @ 1048 1/5/2022

**Review by devotedsouls — APPROVED** [review]

**Comment by Cambridgeport90** [comment]
Awesome.

**Review by phillf — APPROVED** [review]

**Review by phillf — APPROVED** [review]

**Review by devotedsouls — APPROVED** [review]
Approved.

**Pull request merged**
