### PR TITLE
Added Yankton Vehicle Registration Option

### PR DESCRIPTION
**Pull request by Matt4499**

### CODE REVIEW

**Comment by XxROBOTICSxX** [comment]
State is officially called "North Yankton" advise changing from "Yankton" to "North Yankton" for accuracy.

**Comment by termanator1128** [comment]
@Matt4499 Why would we add North Yankton as a state?

**Comment by Cambridgeport90** [comment]
I didn’t even know that was a state? LOL

**Comment by Matt4499** [comment]
North Yankton is a state. Maybe someone wants to roleplay that they're driving a car tagged in North Yankton?

**Comment by XxROBOTICSxX** [comment]
@termanator1128 I recommend the addition of North Yankton to OpenCAD as it is a wholly cosmetic feature to further enhance RP functionality and in no way harms or effects the core functionality of OpenCAD as a whole.

**Comment by termanator1128** [comment]
@XxROBOTICSxX I get the point but that is for states North Yankton itself is not a state. If you want to use North Yankton use where it came from, North Dakota.

**Comment by justinfarmer14** [comment]
Due to internal discussion with will be included on the next update thank you - Farmer

**Pull request merged**
