### PR TITLE
NCIC API Created + Bug Fixes

### PR DESCRIPTION
**Pull request by kevingorman1000**
Fully created the NCIC API. Documentation has been started and is included but subject to change.
Users API will be to follow.
Updated, better documentation will be to follow.

### CODE REVIEW

**Comment by Cambridgeport90** [comment]
If you are in need of some help writing documentation, let me know.

From: kevingorman1000 ***@***.***>
Sent: Tuesday, July 12, 2022 4:51 PM
To: opencad-app/OpenCAD-php ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [opencad-app/OpenCAD-php] NCIC API Created (PR #429)


Fully created the NCIC API. Documentation has been started and is included but subject to change.
Users API will be to follow.
Updated, better documentation will be to follow.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/opencad-app/OpenCAD-php/pull/429

Commit Summary

  *   b9fa8c1<https://github.com/opencad-app/OpenCAD-php/pull/429/commits/b9fa8c1dc6492e9eb114064fee155811a386bbb7> Full NCIC API Created

File Changes

(30 files<https://github.com/opencad-app/OpenCAD-php/pull/429/files>)

  *   M .gitignore<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (5)
  *   A oc-api/docs/css/bootstrap-treeview.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-ac8428deba2bc8326bc64e2738719a3d5a8bcb203dafba413d7d45ec6eb45bd6> (61)
  *   A oc-api/docs/css/bootstrap-treeview.min.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-2db22de83152ae6498830468e549351405e2d8efbd25d7718dde1294c7a65163> (1)
  *   A oc-api/docs/css/main.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-61f49203d1baedf7392ca32616fcdad83c8fac9600ea3513249c483a1fdad1a4> (8729)
  *   A oc-api/docs/css/main.min.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-47654bc2b8f145839ff123eceac945926ff14a24188cbde456c7fafd2bdb268b> (6)
  *   A oc-api/docs/css/postman-api.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-f26c1aef9c0112279a6d366578af7567244ef2160442fdd28329ca92b151de66> (220)
  *   A oc-api/docs/css/postman-api.min.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-d8806939f08134e84a405589c1716f8f079f03ec2222b9884bf4a0ba3aff6d25> (1)
  *   A oc-api/docs/css/postman.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-f3e9ebeb002dfc87d3cf424a533fcb4d810cbdb5d420ebbd440526bd7728cd31> (473)
  *   A oc-api/docs/css/postman.min.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-6a68d30c366ebfbd497c63e0f25035659153fd4fbfdda3adb670d33625d909af> (1)
  *   A oc-api/docs/css/sidebar-themes.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-b8552fc336aac2fbfced31d0f3ac4c248487cce6348c8e2d669cbee356531d8e> (91)
  *   A oc-api/docs/css/sidebar-themes.min.css<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-63ef9c9b3b706ca0b5540ce36c48d8fabe0d9290a4f691acc55302fc8f5d5016> (1)
  *   A oc-api/docs/index.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-978b3b6c3d48ad1e1597f93097ef1e5698945145418df999674c850668b97ed0> (2620)
  *   A oc-api/docs/js/bootstrap-treeview.js<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-694c14f462930286eccc20b94402c87dfd877e97bf4f4669318cc2b8518d5b40> (1266)
  *   A oc-api/docs/js/bootstrap-treeview.min.js<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-270d93ceb9e015465832e03c27a3dc76c18039a36c951460241df33e4dfcda7b> (1)
  *   A oc-api/docs/js/main.js<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-a68dae272a011f15f09372485099357fa9af54e7a4a942f2fd919d8ebd3de85e> (76)
  *   A oc-api/docs/js/main.min.js<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-7f1129c3ae5d9827ac8b7e74d1a41c1b64ad9a6ef8f02082fea7b1eaccec53b9> (1)
  *   M oc-api/v1/config/functions.inc.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-0de6f84cde53ae40c81931fc60f9914e18b27121d4b809b6e4e7f0e8c00e3495> (30)
  *   M oc-api/v1/ncic/ncicarrests.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-465f0400e93b5a242f8e8613521dc50c1905a228316635cc8118acf2b7f81c5e> (302)
  *   M oc-api/v1/ncic/nciccitations.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-42e650a5301a75fda8b344abe04af1b78b9a5540aa58c8bfe578833e5eed1533> (512)
  *   M oc-api/v1/ncic/ncicnames.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-1eef0c6f1b85aae20cfc8e27c268c7b83a42339d1de29f8269322dfacc466072> (360)
  *   M oc-api/v1/ncic/ncicplates.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-e34820bc703454a8da736ac2bcbe09cac22d4465d7da311bd2c55203a5aef97c> (405)
  *   M oc-api/v1/ncic/ncicwarnings.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-11365cbbe39932601606860c1f8692de0200553e8216e9b228d89ac559c2ade8> (348)
  *   M oc-api/v1/ncic/ncicwarrants.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-1a49ba7b4ed5d18b3640ed5f83819478c4739f9130b486add821c67e1e29e57a> (361)
  *   M oc-api/v1/ncic/ncicweapons.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-8de35cfe3f8105c793740a6f1177e0855dea54b27ae49891d732a2f79c988bae> (351)
  *   A oc-api/v1/objects/MISC.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-8494d3b8f8f490195477c905a15e16886bb3314ff850c340f0bccbe0fa8d482e> (47)
  *   M oc-api/v1/objects/NCIC.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-4d4c46a30b979afd9920ce6345819bf76148cf12119db92b379da57161b1c889> (544)
  *   M oc-apps/civilian.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-14c1f064ecd7eac4f4b67089197d61dc63e59a789bd6fd51954fcdb3820edf24> (6)
  *   M oc-content/themes/default/includes/civNav.inc.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-5d3a03e6b6e0020c637fa986f9e732598585f74374a4919ccb9dffb6ace2d7b2> (4)
  *   M oc-content/themes/default/modals/civilian.modals.inc.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-a6c61fed41ba16b22fb6b16daaf1cb69d4aae6f543c345c7587f1811aa58de49> (892)
  *   D test1.php<https://github.com/opencad-app/OpenCAD-php/pull/429/files#diff-2998a078d7e8c75c5a2ff1b08618add24d4e719cdb9fdc08cda3b4aa248fc835> (40)

Patch Links:

  *   https://github.com/opencad-app/OpenCAD-php/pull/429.patch
  *   https://github.com/opencad-app/OpenCAD-php/pull/429.diff

**Comment by kevingorman1000** [comment]
ryGuy has agreed to work on the auto generated one I have. I'd like to work with swagger at some point but having some issues getting it working properly. Something for the future for sure.

**Comment by ItsAGeekThing** [comment]
@kevingorman1000 is this ready to be merged?

**Comment by kevingorman1000** [comment]
Currently, yeah, i still have to finish the other parts of the api  but unsure when I'll get around to it. Worth commiting it now as it resolves some DB error breaking install

**Pull request merged**
