### PR TITLE
Removal of unnecessary vendor assets.

### PR DESCRIPTION
**Pull request by ItsAGeekThing**
~This is a massive change being worked on under my experimental branch.~

This removes every unused asset in the vendors directory. 
Vendor directory went from containing 4,688 items, totaling 86.7 MB down to 595 items, totaling 6.7 MB.

### CODE REVIEW

**Comment by ItsAGeekThing** [comment]
This involves OCPHP-134 and OCPHP-135 on Jira.

**Comment by ItsAGeekThing** [comment]
Closes OCPHP-135

**Comment by ItsAGeekThing** [comment]
Please do not sign-off on this pull request without testing the CAD intensively.
This is a significant removal of assets.

**Comment by phillf** [comment]
Corresponding issues exist in JIRA.

See OCPHP-135 and OCPHP-136

**Review by phillf — APPROVED** [review]

**Pull request merged**
