### PR TITLE
Combined dl_type and dl_status

### PR DESCRIPTION
**Pull request by phillf**
* [#366]  Combined dl_type and dl_status in to one column to equalize table content with header(s).
    * [#366] Moved Driver's License content to after Build as it doesn't describe an attribute of a person. 
    * [#366] It was more consistent with the rest of the headers to have "Build" for the DL column.
    * Reported by @AniTexs
* Removed SQL directory to reduce the number of places SQL templates need to be updated.

### CODE REVIEW

**Comment by phillf** [comment]
I think either use this directory or the OpenCAD-data should be used but not both. choosing one would:
* Reduce potential confusion for EUs.
* Reduce the number of places that have to be updated when game content changes.
* Reduces room for potential errors in content and saves time for maintainers/contributors.

**Comment by devotedsouls** [comment]
This pull request was closed due to the missing files that are necessary for installation.

**Comment by mikespears** [comment]
This PR shouldn't have been closed.

**Comment by ItsAGeekThing** [comment]
I've gone ahead and reopened this so that we can go ahead and receive additional feedback from the community. This pull request covers multiple bug fixes and shouldn't be closed outright, changes can be requested via GitHub. I am going to finish reviewing this when I get back to my workstation.

Thanks for the contribution, @phillf.

**Comment by phillf** [comment]
Closing for sync with upstream.

**Comment by ItsAGeekThing** [comment]
**See #373.**

**Pull request closed without merging**
